# =================================================================
#
# Authors: Francesco Martinelli <francesco.martinelli@ingv.it>
#
# Copyright (c) 2024 Francesco Martinelli
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

import base64
import copy
import logging
import os
from typing import Any, Optional, Tuple
import uuid
import requests
import shutil
import time

from pathlib import Path
from urllib.parse import urljoin, urlparse

from pygeoapi.process.base import (
    BaseProcessor,
    GenericError,
    ProcessorExecuteError,
    ProcessorGenericError,
)

LOGGER = logging.getLogger(__name__)


class BaseRemoteExecutionProcessor(BaseProcessor):
    """
    Base processor to execute code remotely using a designated remote service.

    Overview
    --------
    This processor delegates job execution to an external service
    identified by the configured `url_executor`. The remote service
    is responsible for executing the job and providing execution metadata.

    Remote API Contract
    -------------------
    1) POST /execute
       Content-Type: application/json

       Expected payload:
       {
           'application_params': {
               'job_id': '<string>',
               'synch_execution': <bool, optional>
           },
           'code_input_params': {
               ... arbitrary input parameters ...
           }
       }

       - job_id: unique identifier for the job.
       - synch_execution:
           If True, the service returns after job completion.
           If False, the service returns once the job is accepted.
           Default behavior is synchronous execution.
       - code_input_params:
           Input parameters for the remote execution.
           Supported types: string, list, bool, number.
           Semantics are defined by the remote service.

    2) GET /job_info/<job_id>

       Returns:
       {
           'job_id': '<string>',
           'job_info': {
               'received': '<timestamp>',
               'start_processing': '<timestamp|optional>',
               'end_processing': '<timestamp|optional>',
               'exit_code': '<int|optional>',
               'std_out': '<string|optional>',
               'std_err': '<string|optional>'
           },
           'params': {
               ... effective execution parameters ...
           }
       }

    Filesystem Contract
    -------------------
    The processor and the remote service may share a common directory.
    For each job_id, a folder named <job_id> is used as working directory.

    If the remote service has not the common directory with the processor,
    then all input/output will be exchanged in the request body/response.

    If the remote service has the common directory with the processor,
    then the processor may:
    - Provide input files in the working directory.
    - Retrieve output files generated by the remote execution.

    Execution Result Handling
    --------------------------
    - Outputs are composed from:
        - job_info.std_out
        - generated output files
    - If job_info.exit_code != 0:
        The execution is considered failed and
        job_info.std_err is returned as error message.

    """

    def __init__(self, processor_def: dict, process_metadata: dict):
        """
        Initialize object

        :param processor_def: processor definition
        :param process_metadata: process metadata `dict`

        :returns:
            pygeoapi.processor.base_remote_execution.
                BaseRemoteExecutionProcessor
        """
        super().__init__(processor_def, process_metadata)
        private_processor_dir = processor_def['private_processor_dir']
        self.url_executor = processor_def['url_executor']

        if private_processor_dir is None:
            raise ProcessorGenericError(
                'Undefined \'private_processor_dir\' in configuration.')
        try:
            os.mkdir(private_processor_dir, mode=0o755)
        except FileExistsError:
            pass

        if self.url_executor is None:
            raise ProcessorGenericError(
                'Undefined \'url_executor\' in configuration.')

        self.private_processor_path = Path(private_processor_dir)

        self.polling_time = processor_def.get('polling_time', 3)
#        self.max_waiting_loops = max(
#            0, int(processor_def.get('max_waiting_loops', 1))
#        )

        self.remote_execute_synch = processor_def.get(
            'remote_execute_synch', True
        )
        self.job_id = None

    def set_job_id(self, job_id: str) -> None:
        self.job_id = job_id

    def prepare_input(self, data, working_dir: Path, outputs):
        """
        validate the input and prepare the objet to send to the 'code'

        :param data: inputs data received by the caller.
        Data must be checked they match the metadata definition of 'inputs'.

        NOTE: the logic to pass the received parameters to the 'code' is up
        to the specialised class.

        NOTE: specifically, it is valid also for the "file(s) passed as
        parameter(s) as encoded string":
        it is up to the specialised class to handle them to the 'code'.
        Options could be:
        -) get and save the file(s) to the working directory,
        and pass to the 'code' the filename as parameter;
        -) transfer to the 'code' the files as streams;
        -) other...

        Return the dictionary with the parameters to be passed to the 'code'.
        """
        raise NotImplementedError()

    def prepare_output(self, data, working_dir: Path, outputs):
        """
        Prepare the output object as defined by the metadata definition of
        'outputs'.

        :param data: data dictionary received back from the 'code'
        :param working_dir: directory where to find files produced by the 'code'
        :param outputs: outputs parameter passed with the execution request.
        List of outputs keys, or dictionary of outputs with preference.

        NOTE: the logic to pass back the data received from the 'code' is up
        to the specialised class.

        Return mimetype, process_output
        """
        raise NotImplementedError()

    def _check_output_request(self, requested_output) -> dict:
        """
        Check for errors in output requested,
        and return the expected outputs at the end of processing.
        Currently checking:
        -) name of outputs
        -) property outputTransmission
        """

        if not requested_output:
            # Case of empty outputs.
            # By default should return all outputs defined by the service
            # with the "transmitionMode" set to "value" (the default)
            expected_output = {
                output: {'transmissionMode': 'value'}
                for output in self.metadata.get('outputs', [])
            }
        else:
            # Checking for outputs not passed as dictionary:
            if not isinstance(requested_output, dict):
                raise ProcessorExecuteError(
                    'Invalid outputs: required to be a dictionary.'
                )
            expected_output = copy.deepcopy(requested_output)

            # Checking for request of undefined outputs:
            if set(expected_output) - set(self.metadata['outputs']):
                err_msg = 'Outputs contains unexpected parameters.'
                raise ProcessorExecuteError(err_msg)        

        # Checking for valid transmissionMode parameter
        allowed_modes = self.metadata.get('outputTransmission', [])
        for output_id, output_info in expected_output.items():
            transmission_mode = output_info.setdefault('transmissionMode', 'value')

            if transmission_mode not in allowed_modes:
                raise ProcessorExecuteError(
                    f'Invalid transmissionMode for {output_id}: '
                    f'{transmission_mode}. Allowed values: '
                    f'{allowed_modes}.'
                )
        
        return expected_output

    def execute(self, data: dict, outputs: Optional[dict] = None
                ) -> Tuple[str, Any]:
        """
        The specialized class use a non standard web service to perform the
        elaboration.
        The execute prepare the input for the service,
        then wait for the result (either sync or async, according to the
        configuration of the specific service)
        and finally prepare the output
        """
        if not self.job_id:
            # should be happen only in testing
            raise ProcessorGenericError(
                'Missing call to \'set_job_id()\' before \'execute()\'.')

        working_path = self.private_processor_path / self.job_id
        os.mkdir(working_path, mode=0o755)

        try:
        # check for error on outputs request and get outputs to be provided:
            expected_outputs = self._check_output_request(outputs)
            code_input_params = self.prepare_input(data, working_path, expected_outputs)
        except BaseException as ex:
            shutil.rmtree(working_path)
            raise ex

        # Call the processing server, always synch:
        execute_url = urljoin(self.url_executor, 'execute')
        headers = {'Content-type': 'application/json'}
        response = requests.post(execute_url, json={
          'application_params': {
              'job_id': self.job_id,
              'synch_execution': self.remote_execute_synch
          },
          'code_input_params': code_input_params},
          headers=headers
        )
        if not response.ok:
            try:
                # Unaccepted request: the dir and files are useless:
                shutil.rmtree(working_path)
                # Get returned message
                message = response.json()['Message']
                raise ProcessorExecuteError(message)
            except Exception:
                # If no returned message, get exception message
                raise ProcessorExecuteError(response)

        # Note: response.ok --> thread started
        # otherwise we received an abort().

        if self.remote_execute_synch:
            info = response.json()
        else:
            # Wait the end of the elaboration (using sleep)
#            max_waiting_loops = self.max_waiting_loops + 1
#            while (max_waiting_loops := max_waiting_loops-1) > 0:
            while True:
                time.sleep(self.polling_time)
                execute_url = urljoin(
                    self.url_executor, 'job_info/' + self.job_id
                )
                response = requests.get(execute_url)
                if not response.ok:
                    try:
                        shutil.rmtree(working_path)
                        message = response.json()['Message']
                        raise ProcessorExecuteError(message)
                    except Exception:
                        raise ProcessorExecuteError(response)
                    
                info = response.json()
                if info['job_info']['end_processing']:
                    break

        if info['job_info']['exit_code'] != 0:
            error_msg = (
                f'The job "{info["job_id"]}" exited with code: '
                f'{info["job_info"]["exit_code"]}\n'
                f'Error message:\n{info["job_info"]["std_err"]}'
            )
            logging.error(error_msg)
            # Possibly not return message to client: could contain security info.
            message = (
                f'The job "{info["job_id"]}" '
                f'exited with code {info["job_info"]["exit_code"]} '
                f': {info["job_info"]["std_err"]} '
            )
            # do not remove working_dir for debugging purpose
            raise ProcessorExecuteError(message)
        
        mimetype, process_outputs = self.prepare_output(info, working_path, expected_outputs)
        # content of working_dir no more usefull
        shutil.rmtree(working_path)

        return mimetype, process_outputs
    
    def format_output(self, produced_outputs: dict, user_requested_output):
        """
        Common function for all the subclasses to format the output according
        to the standard.
        
        If only one output is requested, then return the output as expected
        in the process_output, and mimetype according to output definition.
        If multiple output is requested, then mimetyep is multipart/related
        and each part of the process_output will contain one output.
        
        :param self: Description
        :param produced_outputs: dictionary with produced outputs according
        to the client request.
        :type produced_outputs: dict
        :param user_requested_output: outputs parameter passed with the
        execution request.
        List of outputs keys, or dictionary of outputs with preference.

        :returns: mimetype, process_output

        """

        # --- CASE 0: NO OUTPUT ---
# TODO: verify if when user_requested_output={} => Return nothing

        # --- CASE X: ALL REFERENCE
# TODO: when all produced_outputs contains href
        if not any(
            'value' in output
            for output in produced_outputs.values()
        ):
            raise ProcessorExecuteError(
                'All outputs requested by reference: Not yet implemented.'
            )

        # --- CASE 1: ONE OUTPUT ONLY ---
# TODO: verify if when user_requested_output=none => CASE 2
        if len(produced_outputs) == 1:
            output_id, output = next(iter(produced_outputs.items()))
            mimetype = output['mediaType']

            value = output['value']

            # decode base64 if needed
            if output.get('encoding') == 'base64':
                # the "value" is expected to be a "string" of a binary data encoded base64
                body = value
            else:
                LOGGER.debug(f'value = {value}')
                # JSON or text
                if isinstance(value, (dict, list)):
                    body = value
                else:
                    LOGGER.debug(f'isinstance(value, (dict, list) == False')
                    # It is expected to be a string or bytes
                    body = value

            LOGGER.debug(f'returning: mimetype = {mimetype}')
            LOGGER.debug(f'returning: process_output = {body}')
            return mimetype, body

        # --- CASE 2: MULTIPLE OUTPUT -> multipart/related ---
        boundary = f'boundary-{uuid.uuid4()}'
        parts = []

        for output_id, output in produced_outputs.items():
            media_type = output['mediaType']
            if 'value' in output:
                value = output['value']
                # prepare payload. NOTE: type(payload)==bytes
                if output.get('encoding') == 'base64':
                    LOGGER.debug(f'output.get("encoding") == "base64"')
                    # the "value" is expected to be a "string" of a binary data encoded base64
                    payload = value.encode('utf-8')
                    transfer_encoding = 'base64'
                else:
                    if isinstance(value, (dict, list)):
                        import json
                        payload = json.dumps(value).encode('utf-8')
                    else:
                        # It is expected to be a string or bytes
                        if (type(value) == bytes):
                            payload = value
                        payload = value.encode('utf-8')
                    transfer_encoding = '8bit'

                part = (
                    f'--{boundary}\r\n'
                    f'Content-Type: {media_type}\r\n'
                    f'Content-ID: <{output_id}>\r\n'

                    # TODO: Verify if Content-Transfer-Encoding is mandatory,
                    # and in case it is mandatory CHECK if it is correct,
                    # otherwise REMOVE it.
                    f'Content-Transfer-Encoding: {transfer_encoding}\r\n'
                    f'\r\n'
                ).encode('utf-8') + payload + b'\r\n'
            elif 'href' in output:
                payload = b''

                part = (
                    f'--{boundary}\r\n'
                    f'Content-Type: {media_type}\r\n'
                    f'Content-ID: <{output_id}>\r\n'
                    f'Content-Location: {output["href"]}\r\n'

                    # TODO: Verify if Content-Transfer-Encoding is mandatory,
                    # and in case it is mandatory CHECK if it is correct,
                    # otherwise REMOVE it.

                    # We save binary data: transfer_encoding should be binary
                    # in this case, so should not be preset (default) for
                    # the given content type
                    # f'Content-Transfer-Encoding: {transfer_encoding}\r\n'
                    f'\r\n'
                ).encode('utf-8') + payload + b'\r\n'

            parts.append(part)

        # Close multipart
        parts.append(f'--{boundary}--\r\n'.encode('utf-8'))

        body = b''.join(parts)
        mimetype = f'multipart/related; boundary="{boundary}"'

        LOGGER.debug(f'returning: mimetype = {mimetype}')
        LOGGER.debug(f'returning: process_output = {body}')
        return mimetype, body

    def resolveSingleOccurrence(self, occurrence):
        """
        Resolve alternative ways to pass a single input parameter.
        """

        # value is an object
        if isinstance(occurrence, dict):
            if 'value' in occurrence:
                return occurrence['value']

            elif 'href' in occurrence:
                # opzionalmente puoi validare gli attributi ammessi
                allowed_attrs = {'href', 'rel', 'type', 'hreflang', 'title'}
                extra_keys = set(occurrence.keys()) - allowed_attrs
                if extra_keys:
                    err_msg = (
                        f'Invalid attributes for href object: {extra_keys}'
                    )
                    raise GenericError(err_msg)

                err_msg = 'href handling not implemented'
                raise GenericError(err_msg)

            elif 'bbox' in occurrence:
                err_msg = 'bbox handling not implemented'
                raise GenericError(err_msg)

            elif 'collection' in occurrence:
                err_msg = 'collection handling not implemented'
                raise GenericError(err_msg)

            else:
                err_msg = f'Invalid object format'
                raise GenericError(err_msg)

        # value is not a dict
        else:
            return occurrence

    def resolveInputData(self, inputData: dict) -> dict:
        """
        Resolve alternative ways to pass input parameters and check the values.
        """
        result = {}
        for key, occurrences in inputData.items():
            if key not in self.metadata['inputs']:
                err_msg = (f'unexpected input parameter: {key}')
                raise ProcessorExecuteError(err_msg)
            
            maxOccurs = self.metadata['inputs'][key].get('maxOccurs', 1)
            minOccurs = self.metadata['inputs'][key].get('minOccurs', 1)
            schema =  self.metadata['inputs'][key]['schema']

            if maxOccurs > 1:
                if not isinstance(occurrences, list):
                    err_msg = (f'Expected array for input parameter: {key} .')
                    raise ProcessorExecuteError(err_msg)
                n = len(occurrences)
                if not (minOccurs <= n <= maxOccurs):
                    err_msg = (
                        f'Invalid number of occurrences for input parameter "{key}": '
                        f'expected between {minOccurs} and {maxOccurs}, got {n}.'
                    )
                    raise ProcessorExecuteError(err_msg)

                input = []
                for occurrence in occurrences:
                    try:
                        instance = self.resolveSingleOccurrence(occurrence)
                        # TO DO: if resolve to a reference
                        # ################################
                    except GenericError as ex:
                        err_msg = (f'On key {key}: {ex.message}')
                        raise ProcessorExecuteError(err_msg)
                    
                    validation_errors = validate_json(schema, instance)
                    if validation_errors:
                        raise ProcessorExecuteError(validation_errors)

                    input.append(instance)
                
                result[key] = input
                
            else:
                try:
                    instance = self.resolveSingleOccurrence(occurrences)
                    # TO DO: if resolve to a reference
                    # ################################
                except GenericError as ex:
                    err_msg = (f'On key {key}: {ex.message}')
                    raise ProcessorExecuteError(err_msg)

                validation_errors = validate_json(schema, instance)
                if validation_errors:
                    raise ProcessorExecuteError(validation_errors)
                
                result[key] = instance

        return result


    def __repr__(self):
        return f'<BaseRemoteExecutionProcessor> {self.name}'

class BaseRemoteExecutionProcessorLocalReference(BaseRemoteExecutionProcessor):
    """
    BaseRemoteExecutionProcessorLocalReference

    A specialized BaseRemoteExecutionProcessor which handle outputs requested
    by "reference", saving the output to a local directory and providing the
    href for each output.

    For this Processor family:
    - the DIR where to write the output(s) by reference
    is local to the environment of the Processor, and therefore must be
    passed as a configuration parameter.
    - the URL where to read/find the output(s) by reference is
    is defined within the Processor, and therefore must be passed as
    a configuration parameter.

    
    """    

    def __init__(self, processor_def: dict, process_metadata: dict):
        """
        Initialize object

        :param processor_def: processor definition
        :param process_metadata: process metadata `dict`

        :returns:
            pygeoapi.processor.base_remote_execution.
                BaseRemoteExecutionProcessorLocalReference
        """
        super().__init__(processor_def, process_metadata)

        if 'reference' in self.metadata.get('outputTransmission', []):
            try:
                path = Path(processor_def.get('base_reference_dir'))
                self.base_reference_path = path.resolve(strict=True)
            except  (TypeError, FileNotFoundError, PermissionError):
                if len(self.metadata.get('outputTransmission', [])) == 1:
                    raise ProcessorGenericError(
                        'ERROR in configuration file: output allowed only by '
                        'reference and undefined or not existing path for '
                        f'\'base_reference_dir\' for processor {self.name}.')
                else:
                    msg = (f'Processor {self.name} able to return output by '
                        'reference, but in configuration file '
                        '\'base_reference_dir\' undefined or path not existing.'
                        ' Removing output transmition option \'by reference\'')
                    LOGGER.error(msg)
                    self.metadata['outputTransmission'].remove('reference')
        if 'reference' in self.metadata.get('outputTransmission', []):
            try:
                self.base_reference_url = processor_def.get('base_reference_url')
                parsed = urlparse(self.base_reference_url)
                if parsed.scheme not in ('http', 'https') or not parsed.netloc:
                    raise ProcessorGenericError(
                        f'ERROR in configuration file: Invalid URL '
                        f'\'base_reference_url\' for processor {self.name}.')
                if not self.base_reference_url.endswith('/'):
                    self.base_reference_url += '/'
            except  TypeError:
                if len(self.metadata.get('outputTransmission', [])) == 1:
                    raise ProcessorGenericError(
                        'ERROR in configuration file: output allowed only by '
                        'reference and undefined '
                        f'\'base_reference_url\' for processor {self.name}.')
                else:
                    msg = (f'Processor {self.name} able to return output by '
                        'reference, but in configuration file '
                        '\'base_reference_url\' undefined.'
                        ' Removing output transmition option \'by reference\'')
                    LOGGER.error(msg)
                    self.metadata['outputTransmission'].remove('reference')

from jsonschema.validators import Draft202012Validator
def validate_json(schema: dict, instance: dict) -> list:
    """
    Helper function to validate JSON against a JSON Schema

    :param schema: `dict` of JSON Schema
    :paran instance: `dict` of request instance

    :returns: `list` of valiation errors
    """

    validation_errors = []
    LOGGER.debug('Validating input against schema')
    LOGGER.debug(f'Input: {instance}')
    LOGGER.debug(f'Schema: {schema}')
    validator = Draft202012Validator(schema)

    for error in validator.iter_errors(instance):
        LOGGER.debug(f'{error.json_path}: {error.message}')
        validation_errors.append(f'{error.json_path}: {error.message}')

    return validation_errors

# to be used by METADATA returning charts:
CHART_SCHEMA = {
    'type': 'object',
    'required': ['chartType', 'domain', 'series'],
    'properties': {
        'chartType': {
            'type': 'string'
        },
        'domain': {
            'type': 'object',
            'properties': {
                'key': {'type': 'string'},
                'label': {'type': 'string'},
                'unit': {'type': 'string'},
                'values': {
                    'type': 'array',
                    'items': {'type': 'number'}
                }
            },
            'required': ['key', 'label', 'values']
        },
        'series': {
            'type': 'array',
            'items': {
                'type': 'object',
                'properties': {
                    'key': {'type': 'string'},
                    'label': {'type': 'string'},
                    'unit': {'type': 'string'},
                    'values': {
                        'type': 'array',
                        'items': {'type': 'number'}
                    }
                },
                'required': ['key', 'values']
            }
        }
    }
}


